name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: fifth-audio-423920-g2

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: seguimientos-vp
          region: us-central1
          source: .
          flags: |
            --allow-unauthenticated
            --port=8080
            --memory=512Mi
            --service-account=github-deploy@fifth-audio-423920-g2.iam.gserviceaccount.com
            --build-service-account=projects/fifth-audio-423920-g2/serviceAccounts/github-deploy@fifth-audio-423920-g2.iam.gserviceaccount.com
          env_vars: |
            NODE_ENV=production
            GOOGLE_SERVICE_ACCOUNT_EMAIL=data-cls-dim-asignacion@fifth-audio-423920-g2.iam.gserviceaccount.com
            GOOGLE_SPREADSHEET_ID=1MsSVQ9694qRisT5URamzgGFq8KPA949KP5S7E3O6DFU
            GOOGLE_SHEET_NAME=Tareas
            SMTP_FROM_NAME=Seguimientos VP - Admin
            GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}
            SMTP_USER=${{ secrets.SMTP_USER }}
            SMTP_PASS=${{ secrets.SMTP_PASS }}
